# Copyright 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

java_binary(
    name = "hello-buck-java",
    main_class = "com.facebook.buck.demo.HelloBuckJava",
    deps = [":main"],
)

java_library(
    name = "main",
    srcs = glob(["*.java"]),
    annotation_processors = [           "com.google.auto.value.extension.memoized.processor.MemoizedValidator",
          "com.google.auto.value.processor.AutoAnnotationProcessor",
          "com.google.auto.value.processor.AutoOneOfProcessor",
          "com.google.auto.value.processor.AutoValueBuilderProcessor",
          "com.google.auto.value.processor.AutoValueProcessor" ],

    annotation_processor_deps = [ '//jars:auto-value' ],
    provided_deps = [ '//jars:auto-value-annotations' ],
)
